# Not Autogenerated Don't delete
# Packages:
#include:memoir
#include:fontenc
#include:graphicx
#include:xcolor
#include:amsmath
#include:amssymb
#include:amsthm
#include:libertine
#include:avant
#include:inconsolata
#include:newtxmath

# Commands:
\subtitle{title}
\@subtitle#*
\subsubtitle{title}
\@subsubtitle#*
\titlepage
\innertitlepage{imagefile}