# Not Autogenerated Don't delete
# Packages:
#include:memoir
#include:fontenc
#include:graphicx
#include:xcolor
#include:amsmath
#include:amssymb
#include:amsthm
#include:libertine
#include:avant
#include:inconsolata
#include:newtxmath

# commands from loaded packages
\coloneqq#m
\eqqcolon#m

# Commands:
\define{text}#n
\defineindex{text}#n
\subtitle{title}
\@subtitle#*
\subsubtitle{title}
\@subsubtitle#*
\titlepage
\innertitlepage{imagefile}